version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      # Checkout branch
      - checkout
      
      # Build JSON file
      - run: php build.php
      
      # Store JSON artifact
      - run: |
          mkdir /tmp/artifacts
          mv servers.json /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
